name: Debug
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  toast: ^0.1.5
  hive: ^1.4.1+1
  lorem_cutesum: ^1.0.0
  provider: ^4.0.4
  url_launcher: ^5.4.11
  path_provider: ^1.6.10
  hive_flutter: ^0.3.0+2
  image_picker: ^0.6.0+17
  cupertino_icons: ^0.1.3
  permission_handler: ^3.2.0
  easy_contact_picker: ^0.0.2
  md2_tab_indicator: ^1.0.2
  flutter_clean_calendar: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  
  fonts:
  - family: ProductSans
    fonts:
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 200
      - asset: assets/fonts/ProductSans-Light.ttf
        weight: 300
      - asset: assets/fonts/ProductSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/ProductSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 700
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 800
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 900